name: Build & Add Binaries To Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            gcc \
            make \
            libgtk-3-dev \
            libglib2.0-dev \
            libvte-2.91-dev \
            libcjson-dev

      - name: Compile
        run: make production

      - name: Calculate Binary Hash
        run: sha256sum mnta > hashes.txt

      - name: Upload Binary To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mnta
          asset_name: mnta
          asset_content_type: application/octet-stream

      - name: Upload Hashes To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hashes.txt
          asset_name: hashes.txt
          asset_content_type: application/octet-stream
