name: Build & Add Binaries To Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install libgtk-3-dev gir1.2-vte-2.91 libjson-glib-1.0-0

      - name: Compile
        run: make production

      - name: Calculate Binary Hash
        run: sha256sum mnta > hashes.txt

      - name: Upload Binary To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mnta
          asset_name: mnta
          asset_content_type: application/octet-stream

      - name: Upload Hashes To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./hashes.txt
          asset_name: hashes.txt
          asset_content_type: application/octet-stream
